version: 2
updates:
  - package-ecosystem: "devcontainers"
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: daily
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: daily
    groups:
      npm-all:
        patterns:
          - "*" # 全ての依存関係
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: daily
    groups:
      github-actions-all:
        patterns:
          - "*" # 全ての依存関係
